name: Generar y publicar PNG del Código de Conducta

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Necesario para crear releases y subir assets

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2 libpango-1.0-0 libgdk-pixbuf2.0-0 libffi-dev python3-venv

    - name: Configurar entorno Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generar imagen PNG desde SVG
      run: |
        python svg2png.py -i codigo_de_conducta.svg -o codigo_de_conducta.png

    - name: Obtener fecha y hash corto
      id: vars
      run: |
        echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Crear release automática
      uses: softprops/action-gh-release@v2
      with:
        tag_name: auto-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
        name: Build ${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha_short }}
        body: |
          Release generado automáticamente por GitHub Actions.
        files: codigo_de_conducta.png
